name: BuildAdd commentMore actions

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [windows-latest, ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-14]
        python-version: ['3.11']

    steps:
      # Checkout the repo with submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up OpenMP env (macOS)
        if: runner.os == 'macOS'
        run: |
          echo "CXXFLAGS=-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix libomp)/lib -lomp" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_BUILD: "cp311-*"
          MACOSX_DEPLOYMENT_TARGET: "10.13"
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest {project}/test/"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
